**Nombre:** Rafael J. Mateo C.<br>
**Matrícula:** A01793054

**Módulo 5 - Trabajando con numpy**

In [2]:
import numpy as np

In [3]:
a = np.array([0,1,2,3,4]) #Crea un np array

In [4]:
a.size #Tamaño del array

5

In [5]:
a.ndim #Dimensiones del array

1

In [8]:
b = a[0:3] #Slicing
b

array([0, 1, 2])

In [9]:
u = np.array([1,0])
v = np.array([0,1])

z = u+v #Esta operación es mucho más rápida si se hace con una lista de python, ya que habría que utilizar un loop
z

array([1, 1])

In [10]:
#Código anterior sin numpy
z = []
for n,m in zip(u,v):
    z.append(n + m)
    
z

[1, 1]

In [12]:
z = u+v
z*2 #Multiplicando por un escalar

array([2, 2])

In [13]:
z = u*v # Multiplicación
z

array([0, 0])

In [14]:
z = u+1 #Broadcasting
z

array([2, 1])

In [17]:
np.linspace(-2,2, num = 5) #genera números de manera homogenea entre -2 y 2

array([-2., -1.,  0.,  1.,  2.])

**Numpy 2D arrays**

In [19]:
a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
a = np.array(a)
a

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [20]:
a.ndim

2

In [21]:
a.shape

(3, 3)

In [22]:
a.size

9

In [23]:
a[0,0]

11

In [24]:
a[0,0:2]

array([11, 12])

In [26]:
x = np.array ([[1,0], [0,1]])
y = np.array([[2,1], [1,2]])

x + y

array([[3, 1],
       [1, 3]])

In [27]:
x*y #Para usar multiplicación matricial, usar np.dot en su lugar

array([[2, 0],
       [0, 2]])

**Simple APIs**

* Pandas es un ejemplo de API.
* Existen otros APIS, como REST, para comunicarse con apps en el internet. El cliente se comunica con un servidor por medio de reglas
* El método como se comunica el cliente y servidor es por HTTP.
* El cliente envía un request y el servidor devuelve el recurso por medio de un response

**Ejercicios Lab - Módulo V**

Convertir a un array de numpy

In [36]:
a = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
A = np.array(a)

Calcular el tamaño del array

In [37]:
A.size

12

Acceder a los elementos de la primera file y de la primera y segunda columna

In [38]:
A[0,0:2]

array([1, 2])

Multiplicar las matrices con numpy array

In [39]:
B = np.array([[0, 1], [1, 0], [1, 1], [-1, 0]])

In [41]:
np.dot(A,B)

array([[ 1,  4],
       [ 5, 12],
       [ 9, 20]])

Revisar el tipo del array

In [42]:
b = np.array([3.1, 11.02, 6.2, 213.2, 5.2])
b.dtype

dtype('float64')

In [43]:
type(b)

numpy.ndarray

Asignar el 20 al segundo valor del array

In [ ]:
a = np.array([10, 2, 30, 40,50])
a[1] = 20

Imprimir los números pares del array

In [45]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr[1:8:2]

array([2, 4, 6, 8])

Encontrar tamaño, dimensión y shape del array

In [ ]:
b = np.array([10, 20, 30, 40, 50, 60, 70])

In [46]:
b.shape

(5,)

In [47]:
b.size

5

In [50]:
b.ndim

1

In [51]:
a=np.array([0,1])
b=np.array([1,0])
np.dot(a,b)

0

**Calificación de las preguntas**

![Calificación Review Questions](score.png "Calificación Review Questions")